"""initial tables

Revision ID: 7d95217c1c9a
Revises: 
Create Date: 2026-02-08 05:30:10.692318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d95217c1c9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('processed_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('recording_date', sa.Date(), nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_videos_recording_date', 'videos', ['recording_date'], unique=False)
    op.create_index('idx_videos_status', 'videos', ['status'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('segments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=True),
    sa.Column('chunking_method', sa.String(length=20), server_default=sa.text("'embedding'"), nullable=False),
    sa.Column('embedding_indexed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segments_time', 'segments', ['video_id', 'start_time'], unique=False)
    op.create_index('idx_segments_transcript_id', 'segments', ['transcript_id'], unique=False)
    op.create_index('idx_segments_video_id', 'segments', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_segments_video_id', table_name='segments')
    op.drop_index('idx_segments_transcript_id', table_name='segments')
    op.drop_index('idx_segments_time', table_name='segments')
    op.drop_table('segments')
    op.drop_table('transcripts')
    op.drop_index('idx_videos_status', table_name='videos')
    op.drop_index('idx_videos_recording_date', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
